"""Build the data behind ChromaRecover's project page, film and in-browser lab by running ChromaRecover itself.

Writes assets/chromarecover/:
  chromarecover-<version>-py3-none-any.whl  the exact engine the lab runs in the browser (reproducible build of the checkout)
  data.json      versions, wheel hash, gallery results, the decision of each case, benchmarks, tests, documented external runs
  film.json      one recovery traced stage by stage (tiles, colours, every scored hypothesis, the decision), plus its decoy
  gallery/<id>/  input.png and the top candidates' overlay / evidence / mask, as the lab shows them

Every image is generated by ChromaRecover's own generators (chromarecover.synthetic); no third-party picture is used.
The same RecoverConfig as the lab is used, so the browser can be checked against these native results
(tools/chromarecover_parity.py). The checkout must be clean so the recorded commit really is the code that ran.

    python tools/chromarecover_showcase.py --python C:/path/to/venv/python.exe [--repo ../ChromaRecover] [--skip-slow]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "chromarecover"
BENCHMARKS = [("evaluate_synthetic.py", 10, 128), ("evaluate_synthetic.py", 10, 192), ("evaluate_nuisance.py", 20, 160),
              ("evaluate_nuisance.py", 10, 384), ("evaluate_mosaic.py", 4, 192)]   # exactly the CI invocations

# Runs inside the ChromaRecover environment (numpy / OpenCV / Pillow); prints one JSON document.
ENGINE = r'''
import base64, io, json, sys, time
import numpy as np, cv2, PIL
from PIL import Image
import chromarecover
from chromarecover import recover, RecoverConfig
from chromarecover.synthetic import make_polygon_mosaic, make_chromatic_pattern, degrade_camera
from chromarecover.io import decode_image
from chromarecover.geometry import normalize_geometry
from chromarecover.color import build_representations
from chromarecover.quality import assess_quality
from chromarecover.hypotheses import generate_hypotheses
from chromarecover.primitive_distribution import generate_primitive_distribution_hypotheses, _extract_image_primitives
from chromarecover.recovery import score_hypotheses
from chromarecover.api import _select_diverse

out_dir = sys.argv[1]
CONFIG = RecoverConfig(presentation_max_side=768, max_pixels=16_000_000)   # exactly the lab's configuration (assets/chromarecover/engine.js)

def cases():
    m820 = make_polygon_mosaic(size=480, text="820", seed=42, structured=True)
    yield "mosaic-820", m820.image, m820.support_mask, m820.mask, "digital", {"generator": "polygon_mosaic", "text": "820", "seed": 42, "structured": True, "size": 480}
    d820 = make_polygon_mosaic(size=480, text="820", seed=42, structured=False)
    yield "mosaic-820-decoy", d820.image, None, None, "digital", {"generator": "polygon_mosaic", "text": "820", "seed": 42, "structured": False, "size": 480}
    m37 = make_polygon_mosaic(size=480, text="37", seed=43, structured=True)
    yield "mosaic-37", m37.image, m37.support_mask, m37.mask, "digital", {"generator": "polygon_mosaic", "text": "37", "seed": 43, "structured": True, "size": 480}
    dots = make_chromatic_pattern(size=320, text="8", seed=7, structured=True)
    yield "dots-8", dots.image, dots.mask, dots.mask, "digital", {"generator": "chromatic_pattern", "text": "8", "seed": 7, "structured": True, "size": 320}
    dneg = make_chromatic_pattern(size=320, text="8", seed=7, structured=False)
    yield "dots-decoy", dneg.image, None, None, "digital", {"generator": "chromatic_pattern", "text": "8", "seed": 7, "structured": False, "size": 320}
    # drawn by the same generator inside the lab (Pyodide, OpenCV 4.11), which lays the tiles out slightly differently from
    # native OpenCV for the same seed; kept because ChromaRecover passes it as ok on a fragment of the text
    frag = np.asarray(Image.open(f"{sys.argv[2]}/mosaic-2026-s7-browser.png").convert("RGB"))
    frag_support = np.asarray(Image.open(f"{sys.argv[2]}/mosaic-2026-s7-browser-support.png")) > 0
    frag_glyph = make_polygon_mosaic(size=480, text="2026", seed=7, structured=True).mask   # the glyph is identical in both builds
    yield "mosaic-2026-fragment", frag, frag_support, frag_glyph, "digital", {"generator": "polygon_mosaic (in the browser)", "text": "2026", "seed": 7, "structured": True, "size": 480}
    cam = degrade_camera(m820.image, seed=19)
    yield "camera-820", cam, None, None, "auto", {"generator": "degrade_camera(polygon_mosaic 820)", "seed": 19, "size": 480}
    yield "blank", np.full((320, 320, 3), (171, 128, 96), np.uint8), None, None, "digital", {"generator": "uniform colour"}
    y, x = np.mgrid[0:320, 0:320] / 319.0
    ramp = np.stack([60 + 150 * x, 90 + 110 * y, 170 - 80 * x * y], -1).astype(np.uint8)
    yield "ramp", ramp, None, None, "digital", {"generator": "smooth RGB ramp"}

def overlap(a, b):
    """Selected pixels against the generator's truth: precision (share of the selection that is truth), recall, IoU."""
    if a is None or b is None:
        return None
    if a.shape != b.shape:
        a = cv2.resize(a.astype(np.uint8), (b.shape[1], b.shape[0]), interpolation=cv2.INTER_NEAREST).astype(bool)
    a, b = a.astype(bool), b.astype(bool)
    inter, sel, truth, union = np.logical_and(a, b).sum(), a.sum(), b.sum(), np.logical_or(a, b).sum()
    return {"precision": round(float(inter / sel), 4) if sel else None, "recall": round(float(inter / truth), 4) if truth else None,
            "iou": round(float(inter / union), 4) if union else None}

def save_img(arr, path, quality=None):
    im = Image.fromarray(arr)
    if quality:
        im.save(path, "WEBP", quality=quality, method=6)
    else:
        im.save(path, "PNG", optimize=True)

def rounded(d):
    return {k: (round(float(v), 6) if isinstance(v, (int, float, np.floating)) and not isinstance(v, bool) else v) for k, v in d.items()}

gallery = []
for cid, image, support, glyph, mode, meta in cases():
    folder = f"{out_dir}/gallery/{cid}"
    import os; os.makedirs(folder, exist_ok=True)
    save_img(image, f"{folder}/input.png")
    t = time.perf_counter()
    r = recover(image, mode=mode, semantics="auto", top_k=3, config=CONFIG)
    wall = time.perf_counter() - t
    cands = []
    for c in r.candidates:
        n = c.rank
        save_img(c.overlay, f"{folder}/overlay_{n}.webp", 82)
        save_img((np.clip(c.evidence_map, 0, 1) * 255).astype(np.uint8), f"{folder}/evidence_{n}.webp", 82)
        save_img((c.mask.astype(np.uint8) * 255), f"{folder}/mask_{n}.png")
        save_img((c.structure_mask.astype(np.uint8) * 255), f"{folder}/structure_{n}.png")
        cands.append({"rank": n, "id": c.id, "source": c.source_hypothesis, "structure": round(c.structure_score, 6), "capture": round(c.capture_confidence, 6),
                      "decision": round(c.decision_confidence, 6), "warnings": c.warnings, "metrics": rounded(c.metrics),
                      "semantics": None if not c.semantics else {k: c.semantics.get(k) for k in ("hypothesis", "confidence", "accepted", "reason")},
                      "truth_support": overlap(c.mask, support), "truth_glyph": overlap(c.structure_mask, glyph)})
    q = r.quality
    gallery.append({"id": cid, "meta": meta, "mode": mode, "mode_resolved": r.input_info.get("mode_resolved"), "status": r.status,
                    "width": int(image.shape[1]), "height": int(image.shape[0]), "candidates": cands,
                    "quality": {k: round(float(getattr(q, k)), 4) for k in ("blur", "clipping", "glare", "color_spread", "moire", "banding", "texture_support")} | {"warnings": q.warnings},
                    "semantics": r.semantics, "timing_ms": r.timing_ms, "wall_s": round(wall, 3), "config_fingerprint": r.config_fingerprint,
                    "has_truth": support is not None})

def trace(image):
    """The recover() stages, called one by one (internal API of this pinned commit), for the film."""
    s = CONFIG
    decoded = decode_image(image, max_pixels=s.max_pixels, max_file_bytes=s.max_file_bytes, max_icc_profile_bytes=s.max_icc_profile_bytes, analysis_max_side=s.analysis_max_side)
    geometry = normalize_geometry(decoded.rgb, mode="digital", max_side=s.analysis_max_side)
    rgb = geometry.rgb
    colors = build_representations(rgb, s.local_sigma_ratio)
    quality = assess_quality(rgb, colors, blur_rgb=decoded.rgb)
    hyps = generate_hypotheses(colors.feature_sets, s)
    prim = generate_primitive_distribution_hypotheses(colors.lab, s)
    hyps.extend(prim.hypotheses)
    scored = score_hypotheses(hyps, colors, quality, invalid_mask=np.zeros(rgb.shape[:2], bool))
    chosen = _select_diverse(scored, 3)
    return rgb, colors, prim, hyps, scored, chosen

def bits(mask, side=24):
    small = cv2.resize(mask.astype(np.uint8), (side, side), interpolation=cv2.INTER_AREA) > 0
    return base64.b64encode(np.packbits(small.ravel())).decode()

def u8(arr, side=96):
    small = cv2.resize(arr.astype(np.float32), (side, side), interpolation=cv2.INTER_AREA)
    return base64.b64encode(np.clip(small * 255, 0, 255).astype(np.uint8).tobytes()).decode()

def film_case(image, official):
    rgb, colors, prim, hyps, scored, chosen = trace(image)
    best = chosen[0]
    lab = colors.lab
    tiles = _extract_image_primitives(lab)[1]
    h, w = rgb.shape[:2]
    win = cv2.resize(best.mask.astype(np.uint8), (w, h), interpolation=cv2.INTER_NEAREST).astype(bool) if best.mask.shape != (h, w) else best.mask
    rng = np.random.default_rng(3)
    idx = rng.choice(h * w, size=min(2400, h * w), replace=False)
    ys, xs = np.unravel_index(idx, (h, w))
    fam = sorted({x.family for x in scored})
    return {
        "analysis": [int(w), int(h)],
        "tiles": [[round(p.center_x / w, 4), round(p.center_y / h, 4), round(p.mean_lab[0], 2), round(p.mean_lab[1], 2), round(p.mean_lab[2], 2), int(p.area), int(win[int(p.center_y), int(p.center_x)])] for p in tiles],
        "pixels": [[round(float(lab[y, x, 0]), 1), round(float(lab[y, x, 1]), 1), round(float(lab[y, x, 2]), 1), int(win[y, x])] for y, x in zip(ys, xs)],
        "hypotheses_generated": len(hyps), "families": fam,
        "scored": [{"source": x.source, "family": x.family, "score": round(x.score, 5), "confidence": round(x.confidence, 5), "occupancy": round(x.metrics.get("occupancy", 0), 4),
                    "bits": bits(x.mask)} for x in scored],
        "chosen": [x.source for x in chosen],
        "evidence": u8(official.best.evidence_map) if official.best is not None else None,
        "mask": bits(official.best.mask, 96) if official.best is not None else None,
        "status": official.status, "best": None if official.best is None else {"source": official.best.source_hypothesis, "structure": round(official.best.structure_score, 6),
                  "capture": round(official.best.capture_confidence, 6), "decision": round(official.best.decision_confidence, 6), "warnings": official.best.warnings, "metrics": rounded(official.best.metrics)},
        "semantics": official.semantics, "threshold": CONFIG.confidence_threshold, "ambiguity_margin": CONFIG.ambiguity_margin,
        "agrees_with_recover": official.best is not None and best.source == official.best.source_hypothesis,
    }

m820 = make_polygon_mosaic(size=480, text="820", seed=42, structured=True)
d820 = make_polygon_mosaic(size=480, text="820", seed=42, structured=False)
film = {"positive": film_case(m820.image, recover(m820.image, mode="digital", semantics="auto", top_k=3, config=CONFIG)),
        "decoy": film_case(d820.image, recover(d820.image, mode="digital", semantics="auto", top_k=3, config=CONFIG))}
json.dump(film, open(f"{out_dir}/film.json", "w", encoding="utf-8"), separators=(",", ":"))
print(json.dumps({"gallery": gallery, "runtime": {"python": sys.version.split()[0], "numpy": np.__version__, "opencv": cv2.__version__, "pillow": PIL.__version__},
                  "algorithm_version": chromarecover.__dict__.get("ALGORITHM_VERSION") or None, "version": chromarecover.__version__,
                  "config": {"confidence_threshold": CONFIG.confidence_threshold, "ambiguity_margin": CONFIG.ambiguity_margin, "analysis_max_side": CONFIG.analysis_max_side,
                             "presentation_max_side": CONFIG.presentation_max_side, "fingerprint": CONFIG.fingerprint()},
                  "film_agrees": [film["positive"]["agrees_with_recover"], film["decoy"]["agrees_with_recover"]]}))
'''


def git(repo: Path, *args: str) -> str:
    return subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True, text=True).stdout


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=str(ROOT.parent / "ChromaRecover"))
    ap.add_argument("--python", required=True, help="a Python with ChromaRecover's checkout installed (non-editable is fine)")
    ap.add_argument("--skip-slow", action="store_true", help="reuse benchmark and test results already in data.json")
    a = ap.parse_args()
    repo = Path(a.repo).resolve()
    if git(repo, "status", "--porcelain").strip():
        sys.exit(f"{repo} has uncommitted changes; the page must name the exact code that produced it")
    commit = git(repo, "rev-parse", "HEAD").strip()
    epoch = git(repo, "log", "-1", "--format=%ct").strip()
    env = {**os.environ, "PYTHONIOENCODING": "utf-8", "PYTHONDONTWRITEBYTECODE": "1", "SOURCE_DATE_EPOCH": epoch}
    installed = subprocess.run([a.python, "-c", "import chromarecover, sys; print(chromarecover.__version__, chromarecover.__file__)"],
                               capture_output=True, text=True, env=env, check=True).stdout.split()
    source_version = re.search(r'__version__\s*=\s*"([^"]+)"', (repo / "src" / "chromarecover" / "_version.py").read_text(encoding="utf-8")).group(1)
    if installed[0] != source_version:
        sys.exit(f"the environment has ChromaRecover {installed[0]} but the checkout is {source_version}; reinstall it")
    old = json.loads((OUT / "data.json").read_text(encoding="utf-8")) if (OUT / "data.json").is_file() else {}

    with tempfile.TemporaryDirectory(prefix="cr-showcase-") as t:
        tmp = Path(t)
        # ---- the engine the lab downloads: a reproducible wheel of this exact commit ----
        subprocess.run(["uv", "build", "--wheel", "--out-dir", str(tmp / "dist"), str(repo)], env=env, check=True, capture_output=True)
        wheel = next((tmp / "dist").glob("chromarecover-*.whl"))
        staged = tmp / "site"
        (staged / "gallery").mkdir(parents=True)
        shutil.copy2(wheel, staged / wheel.name)
        # ---- gallery and film, from the installed package ----
        r = subprocess.run([a.python, "-c", ENGINE, str(staged), str(OUT / "fixtures")], capture_output=True, text=True, encoding="utf-8", env=env)
        if r.returncode:
            sys.exit(f"engine run failed: {r.stderr[-1500:]}")
        engine = json.loads(r.stdout)
        if not all(engine["film_agrees"]):
            sys.exit("the traced stages chose a different best candidate than recover(); the film would misstate the run")
        # ---- the CI benchmark gates and the test suite ----
        if a.skip_slow and old.get("benchmarks"):
            benchmarks, tests = old["benchmarks"], old["tests"]
        else:
            benchmarks = []
            for script, count, size in BENCHMARKS:
                b = subprocess.run([a.python, str(repo / "benchmark" / script), "--count", str(count), "--size", str(size), "--assert-thresholds"],
                                   cwd=repo, capture_output=True, text=True, encoding="utf-8", env=env)
                benchmarks.append({"script": script, "count": count, "size": size, "passed": b.returncode == 0, "result": json.loads(b.stdout)})
            xml = tmp / "junit.xml"
            subprocess.run([a.python, "-m", "pytest", "-q", "-p", "no:cacheprovider", f"--junitxml={xml}"], cwd=repo, capture_output=True, text=True, env=env)
            suite = ET.parse(xml).getroot()
            suite = suite if suite.tag == "testsuite" else suite.find("testsuite")
            n, skipped, failed = int(suite.get("tests")), int(suite.get("skipped")), int(suite.get("failures")) + int(suite.get("errors"))
            if failed:
                sys.exit(f"{failed} ChromaRecover tests failed; fix the checkout before publishing its numbers")
            tests = {"collected": n, "passed": n - skipped, "skipped": skipped, "seconds": round(float(suite.get("time")))}
        if git(repo, "status", "--porcelain").strip():
            sys.exit(f"running ChromaRecover left changes in {repo}; not publishing")

        # ---- documented external runs (their data cannot be redistributed, so they are quoted, not re-run) ----
        ext = (repo / "docs" / "external-datasets.md").read_text(encoding="utf-8")
        sd = re.search(r"detected (\d+)/(\d+) frames, with median IoU (\d+\.\d+) and maximum normalized corner RMSE\s+(\d+\.\d+)", ext)
        cb = re.search(r"candidates\s+for (\d+)/(\d+), accepted (\d+)/(\d+) digit readings, got all (\d+) accepted readings exactly right, and\s+made zero false acceptances", ext)
        if not (sd and cb):
            sys.exit("docs/external-datasets.md changed wording; update the patterns before quoting its results")

        OUT.mkdir(parents=True, exist_ok=True)
        for stale in OUT.glob("chromarecover-*.whl"):
            stale.unlink()
        if (OUT / "gallery").exists():
            shutil.rmtree(OUT / "gallery")
        shutil.copytree(staged / "gallery", OUT / "gallery")
        shutil.copy2(staged / wheel.name, OUT / wheel.name)
        shutil.copy2(staged / "film.json", OUT / "film.json")

    digest = hashlib.sha256((OUT / wheel.name).read_bytes()).hexdigest()
    data = {
        "source": {"repo": "https://github.com/niansia/ChromaRecover", "commit": commit, "run": date.today().isoformat(), "version": engine["version"]},
        "wheel": {"file": wheel.name, "sha256": digest, "bytes": (OUT / wheel.name).stat().st_size},
        "native": engine["runtime"], "config": engine["config"], "gallery": engine["gallery"],
        "benchmarks": benchmarks, "tests": tests,
        "external": {"smartdoc": {"detected": int(sd.group(1)), "frames": int(sd.group(2)), "median_iou": float(sd.group(3)), "max_rmse": float(sd.group(4))},
                     "colorblindness": {"candidates": int(cb.group(1)), "images": int(cb.group(2)), "accepted": int(cb.group(3)), "correct": int(cb.group(5)), "false_accept": 0}},
        # a parity run (tools/chromarecover_parity.py) stays valid only for the same engine, configuration and gallery
        "parity": old.get("parity") if (old.get("wheel", {}).get("sha256") == digest and old.get("config", {}).get("fingerprint") == engine["config"]["fingerprint"]
                                          and [g["id"] for g in old.get("gallery", [])] == [g["id"] for g in engine["gallery"]]) else None,
    }
    text = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    for leak in ("Users", "AppData", "cr-showcase-"):
        if leak in text:
            sys.exit(f"refusing to write: output still contains {leak!r}")
    (OUT / "data.json").write_text(text + "\n", encoding="utf-8")
    print(f"wrote assets/chromarecover (wheel {digest[:12]}) from ChromaRecover {engine['version']} @ {commit[:12]}: "
          + ", ".join(f"{g['id']} {g['status']}" for g in engine["gallery"])
          + f"; benchmarks {sum(b['passed'] for b in benchmarks)}/{len(benchmarks)}, tests {tests['passed']}/{tests['collected']}")


if __name__ == "__main__":
    main()
